default:
  image: ubuntu:20.04
  before_script:
    - ln -snf /usr/share/zoneinfo/Europe/London /etc/localtime && echo Europe/London > /etc/timezone
    - apt-get update
    - apt-get install -y daps epubcheck optipng checkbot lsb-release dvipng imagemagick-6.q16 latexmk libjs-mathjax texlive-fonts-recommended texlive-latex-base texlive-latex-recommended texlive-latex-extra xzdec
    - lsb_release -a
    - daps --version

stages:
    - Doc Generation

ddrescuegui:
  stage: Doc Generation
  script:
    - daps -d ./DC-daps-ddrescue-gui html
    - ./ddrescue-gui_copy_icons_html.sh
    - ./ddrescue-gui_set_viewport_html.sh
    - daps -d ./DC-daps-ddrescue-gui epub
    - daps -d ./DC-daps-ddrescue-gui pdf

diskverifier:
  stage: Doc Generation
  script:
    - daps -d ./DC-daps-diskverifier html
    - ./diskverifier_copy_icons_html.sh
    - ./diskverifier_set_viewport_html.sh
    - daps -d ./DC-daps-diskverifier epub
    - daps -d ./DC-daps-diskverifier pdf
